-- Intentionally no-op.
-- The application schema is managed by Flyway migrations under src/main/resources/db/migration.
-- Keep this file mounted for Docker compatibility, but do not create tables here; otherwise
-- Flyway baseline-on-migrate can skip the real versioned migrations on a fresh container.
