package com.jinmo.aiwriting.ai.provider;

public enum AIProviderErrorCode {
    AUTH_ERROR,
    MODEL_NOT_FOUND,
    INVALID_BASE_URL,
    INVALID_PROVIDER_CONFIG,
    RATE_LIMIT,
    NETWORK_TIMEOUT,
    NETWORK_ERROR,
    PROVIDER_5XX,
    STRUCTURED_OUTPUT_FAILED,
    CONTENT_POLICY_BLOCKED,
    UNKNOWN_ERROR
}
